// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Mock Supabase Client for local development without credentials
const createMockClient = () => {
  console.warn("Supabase credentials missing. Using mock client.");

  let listeners: ((event: string, session: any) => void)[] = [];
  let currentSession: any = null;

  const notifyListeners = (event: string, session: any) => {
    listeners.forEach(l => l(event, session));
  };

  return {
    auth: {
      onAuthStateChange: (callback: (event: string, session: any) => void) => {
        listeners.push(callback);
        // Trigger initial state if session exists
        if (currentSession) {
          callback('SIGNED_IN', currentSession);
        }
        return {
          data: {
            subscription: {
              unsubscribe: () => {
                listeners = listeners.filter(l => l !== callback);
              }
            }
          }
        };
      },
      getSession: async () => ({ data: { session: currentSession } }),
      signInWithPassword: async () => {
        const user = { id: 'mock-user-id', email: 'admin@example.com' };
        currentSession = { user };
        notifyListeners('SIGNED_IN', currentSession);
        return { data: { user, session: currentSession }, error: null };
      },
      signUp: async () => {
        const user = { id: 'mock-user-id', email: 'admin@example.com' };
        currentSession = { user };
        notifyListeners('SIGNED_IN', currentSession);
        return { data: { user, session: currentSession }, error: null };
      },
      signOut: async () => {
        currentSession = null;
        notifyListeners('SIGNED_OUT', null);
        return { error: null };
      },
    },
    from: () => ({
      select: () => ({
        eq: () => ({
          maybeSingle: async () => ({ data: null, error: null }),
          single: async () => ({ data: null, error: null }),
        }),
        order: () => ({ data: [], error: null }),
      }),
    }),
  } as any;
};

export const supabase = (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY)
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  })
  : createMockClient();